# Generated by Django 4.1.2 on 2022-10-26 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Município')),
                ('cep', models.CharField(blank=True, max_length=40, null=True, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=254, null=True, verbose_name='Endereço')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=254, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido')),
                ('cell', models.CharField(blank=True, max_length=30, null=True, verbose_name='Celular')),
                ('cpf', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número do Documento')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('genre', models.IntegerField(choices=[(1, 'Feminino'), (2, 'Masculino'), (3, 'Não responder')], default=3, verbose_name='Gênero')),
                ('notify_email', models.BooleanField(default=True, verbose_name='Notificação por Email')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfil.address', verbose_name='Endereço')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
