# Generated by Django 4.1.2 on 2023-03-18 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular')),
                ('cpf', models.CharField(max_length=11, null=True, verbose_name='CPF')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('genre', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não responder')], default='N', max_length=1, verbose_name='Gênero')),
                ('notify_email', models.BooleanField(default=True, verbose_name='Notificação por Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], max_length=200, null=True, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cidade')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('address', models.CharField(blank=True, max_length=254, null=True, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=254, null=True, verbose_name='Complemento')),
                ('selected', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='perfil.perfil', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
            },
        ),
    ]
