# Generated by Django 4.1.2 on 2023-01-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_perfil_coupon_alter_perfil_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='address',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='coupon',
        ),
        migrations.AddField(
            model_name='address',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil', verbose_name='perfil'),
        ),
    ]
