# Generated by Django 4.1.2 on 2022-11-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_remove_perfil_surname_alter_address_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='genre',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não responder')], default='N', max_length=1, verbose_name='Gênero'),
        ),
    ]
