# Generated by Django 4.1.2 on 2022-12-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_perfil_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cell',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
