# Generated by Django 4.1.2 on 2023-01-30 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_remove_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='perfil.perfil', verbose_name='perfil'),
        ),
    ]
