# Generated by Django 4.1.2 on 2023-01-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='perfil',
        ),
    ]
