# Generated by Django 4.1.2 on 2023-02-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_alter_coupon_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
