# Generated by Django 4.1.2 on 2022-10-26 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_options_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.address', verbose_name='Endereço'),
        ),
    ]
