# Generated by Django 4.1.2 on 2022-10-26 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_perfil_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.address', verbose_name='Endereço'),
        ),
    ]
