# Generated by Django 4.1.2 on 2022-10-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change',
            field=models.BooleanField(default=False),
        ),
    ]
