# Generated by Django 4.1.2 on 2022-10-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_perfil_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='address',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
