# Generated by Django 4.1.2 on 2022-10-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_perfil_address_remove_perfil_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
    ]
