# Generated by Django 4.1.2 on 2022-11-04 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_perfil_logincodeverification_login_code_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logincodeverification',
            old_name='login_code_verification',
            new_name='user',
        ),
    ]
