# Generated by Django 4.1.2 on 2022-11-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_login_code_verification_logincodeverification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twofa',
            field=models.BooleanField(default=False, verbose_name='Autenticação em duas etapas'),
        ),
    ]
