# Generated by Django 4.1.2 on 2023-01-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_address_alter_order_cep_alter_order_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='perfil',
        ),
    ]
