# Generated by Django 4.1.2 on 2023-01-30 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_address_perfil'),
        ('coupon', '0004_coupon_perfil'),
        ('order', '0006_rename_user_order_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupon.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='perfil.perfil'),
        ),
    ]
